In [16]:
import pandas as pd

# show all rows when printin

import numpy as np

In [19]:
dirty_df = pd.read_csv(r"C:\Users\User\Desktop\0 or not\speeddating.csv")

In [20]:
# I want to get a feel for what the data looks like
dirty_df.head()

,has_null,wave,gender,age,age_o,d_age,d_d_age,race,race_o,samerace,...,d_expected_num_interested_in_me,d_expected_num_matches,like,guess_prob_liked,d_like,d_guess_prob_liked,met,decision,decision_o,match
0,b'',1.0,b'female',21.0,27.0,6.0,b'[4-6]',b'Asian/Pacific Islander/Asian-American',b'European/Caucasian-American',b'0',...,b'[0-3]',b'[3-5]',7.0,6.0,b'[6-8]',b'[5-6]',0.0,b'1',b'0',b'0'
1,b'',1.0,b'female',21.0,22.0,1.0,b'[0-1]',b'Asian/Pacific Islander/Asian-American',b'European/Caucasian-American',b'0',...,b'[0-3]',b'[3-5]',7.0,5.0,b'[6-8]',b'[5-6]',1.0,b'1',b'0',b'0'
2,b'',1.0,b'female',21.0,22.0,1.0,b'[0-1]',b'Asian/Pacific Islander/Asian-American',b'Asian/Pacific Islander/Asian-American',b'1',...,b'[0-3]',b'[3-5]',7.0,NaN,b'[6-8]',b'[0-4]',1.0,b'1',b'1',b'1'
3,b'',1.0,b'female',21.0,23.0,2.0,b'[2-3]',b'Asian/Pacific Islander/Asian-American',b'European/Caucasian-American',b'0',...,b'[0-3]',b'[3-5]',7.0,6.0,b'[6-8]',b'[5-6]',0.0,b'1',b'1',b'1'
4,b'',1.0,b'female',21.0,24.0,3.0,b'[2-3]',b'Asian/Pacific Islander/Asian-American',b'Latino/Hispanic American',b'0',...,b'[0-3]',b'[3-5]',6.0,6.0,b'[6-8]',b'[5-6]',0.0,b'1',b'1',b'1'

In [21]:
# I want to see the columns
dirty_df.columns

Index(['has_null', 'wave', 'gender', 'age', 'age_o', 'd_age', 'd_d_age',
       'race', 'race_o', 'samerace',
       ...
       'd_expected_num_interested_in_me', 'd_expected_num_matches', 'like',
       'guess_prob_liked', 'd_like', 'd_guess_prob_liked', 'met', 'decision',
       'decision_o', 'match'],
      dtype='object', length=123)

In [22]:
# remove columns that start with "d_"
for col in list(dirty_df.columns):       # wrap in list() so dropping inside loop wonâ€™t mess up the iterator
    if col.startswith("d_"):
        dirty_df.drop(col, axis=1, inplace=True)

In [23]:
dirty_df.columns

Index(['has_null', 'wave', 'gender', 'age', 'age_o', 'race', 'race_o',
       'samerace', 'importance_same_race', 'importance_same_religion', 'field',
       'pref_o_attractive', 'pref_o_sincere', 'pref_o_intelligence',
       'pref_o_funny', 'pref_o_ambitious', 'pref_o_shared_interests',
       'attractive_o', 'sinsere_o', 'intelligence_o', 'funny_o', 'ambitous_o',
       'shared_interests_o', 'attractive_important', 'sincere_important',
       'intellicence_important', 'funny_important', 'ambtition_important',
       'shared_interests_important', 'attractive', 'sincere', 'intelligence',
       'funny', 'ambition', 'attractive_partner', 'sincere_partner',
       'intelligence_partner', 'funny_partner', 'ambition_partner',
       'shared_interests_partner', 'sports', 'tvsports', 'exercise', 'dining',
       'museums', 'art', 'hiking', 'gaming', 'clubbing', 'reading', 'tv',
       'theater', 'movies', 'concerts', 'music', 'shopping', 'yoga',
       'interests_correlate', 'expected_happy_with_sd_people',
       'expected_num_interested_in_me', 'expected_num_matches', 'like',
       'guess_prob_liked', 'met', 'decision', 'decision_o', 'match'],
      dtype='object')

In [24]:
dirty_df.drop(['wave'], axis=1,inplace=True)

In [25]:
dirty_df.columns

Index(['has_null', 'gender', 'age', 'age_o', 'race', 'race_o', 'samerace',
       'importance_same_race', 'importance_same_religion', 'field',
       'pref_o_attractive', 'pref_o_sincere', 'pref_o_intelligence',
       'pref_o_funny', 'pref_o_ambitious', 'pref_o_shared_interests',
       'attractive_o', 'sinsere_o', 'intelligence_o', 'funny_o', 'ambitous_o',
       'shared_interests_o', 'attractive_important', 'sincere_important',
       'intellicence_important', 'funny_important', 'ambtition_important',
       'shared_interests_important', 'attractive', 'sincere', 'intelligence',
       'funny', 'ambition', 'attractive_partner', 'sincere_partner',
       'intelligence_partner', 'funny_partner', 'ambition_partner',
       'shared_interests_partner', 'sports', 'tvsports', 'exercise', 'dining',
       'museums', 'art', 'hiking', 'gaming', 'clubbing', 'reading', 'tv',
       'theater', 'movies', 'concerts', 'music', 'shopping', 'yoga',
       'interests_correlate', 'expected_happy_with_sd_people',
       'expected_num_interested_in_me', 'expected_num_matches', 'like',
       'guess_prob_liked', 'met', 'decision', 'decision_o', 'match'],
      dtype='object')

In [26]:
dirty_df.head()

,has_null,gender,age,age_o,race,race_o,samerace,importance_same_race,importance_same_religion,field,...,interests_correlate,expected_happy_with_sd_people,expected_num_interested_in_me,expected_num_matches,like,guess_prob_liked,met,decision,decision_o,match
0,b'',b'female',21.0,27.0,b'Asian/Pacific Islander/Asian-American',b'European/Caucasian-American',b'0',2.0,4.0,b'Law',...,0.14,3.0,2.0,4.0,7.0,6.0,0.0,b'1',b'0',b'0'
1,b'',b'female',21.0,22.0,b'Asian/Pacific Islander/Asian-American',b'European/Caucasian-American',b'0',2.0,4.0,b'Law',...,0.54,3.0,2.0,4.0,7.0,5.0,1.0,b'1',b'0',b'0'
2,b'',b'female',21.0,22.0,b'Asian/Pacific Islander/Asian-American',b'Asian/Pacific Islander/Asian-American',b'1',2.0,4.0,b'Law',...,0.16,3.0,2.0,4.0,7.0,NaN,1.0,b'1',b'1',b'1'
3,b'',b'female',21.0,23.0,b'Asian/Pacific Islander/Asian-American',b'European/Caucasian-American',b'0',2.0,4.0,b'Law',...,0.61,3.0,2.0,4.0,7.0,6.0,0.0,b'1',b'1',b'1'
4,b'',b'female',21.0,24.0,b'Asian/Pacific Islander/Asian-American',b'Latino/Hispanic American',b'0',2.0,4.0,b'Law',...,0.21,3.0,2.0,4.0,6.0,6.0,0.0,b'1',b'1',b'1'

In [27]:
def decode_if_bytes(x):
    if isinstance(x, (bytes, bytearray)):
        return x.decode('utf-8')     # or whatever encoding you need
    return x

dirty_df['gender'] = dirty_df['gender'].apply(decode_if_bytes)

In [28]:
dirty_df.head()

,has_null,gender,age,age_o,race,race_o,samerace,importance_same_race,importance_same_religion,field,...,interests_correlate,expected_happy_with_sd_people,expected_num_interested_in_me,expected_num_matches,like,guess_prob_liked,met,decision,decision_o,match
0,b'',b'female',21.0,27.0,b'Asian/Pacific Islander/Asian-American',b'European/Caucasian-American',b'0',2.0,4.0,b'Law',...,0.14,3.0,2.0,4.0,7.0,6.0,0.0,b'1',b'0',b'0'
1,b'',b'female',21.0,22.0,b'Asian/Pacific Islander/Asian-American',b'European/Caucasian-American',b'0',2.0,4.0,b'Law',...,0.54,3.0,2.0,4.0,7.0,5.0,1.0,b'1',b'0',b'0'
2,b'',b'female',21.0,22.0,b'Asian/Pacific Islander/Asian-American',b'Asian/Pacific Islander/Asian-American',b'1',2.0,4.0,b'Law',...,0.16,3.0,2.0,4.0,7.0,NaN,1.0,b'1',b'1',b'1'
3,b'',b'female',21.0,23.0,b'Asian/Pacific Islander/Asian-American',b'European/Caucasian-American',b'0',2.0,4.0,b'Law',...,0.61,3.0,2.0,4.0,7.0,6.0,0.0,b'1',b'1',b'1'
4,b'',b'female',21.0,24.0,b'Asian/Pacific Islander/Asian-American',b'Latino/Hispanic American',b'0',2.0,4.0,b'Law',...,0.21,3.0,2.0,4.0,6.0,6.0,0.0,b'1',b'1',b'1'

In [29]:
dirty_df['gender'] = (
    dirty_df['gender']
    .astype(str)
    .str.lstrip("b'")   # removes any leading b or '
    .str.rstrip("'")    # removes trailing '
)

In [30]:
dirty_df.head()

,has_null,gender,age,age_o,race,race_o,samerace,importance_same_race,importance_same_religion,field,...,interests_correlate,expected_happy_with_sd_people,expected_num_interested_in_me,expected_num_matches,like,guess_prob_liked,met,decision,decision_o,match
0,b'',female,21.0,27.0,b'Asian/Pacific Islander/Asian-American',b'European/Caucasian-American',b'0',2.0,4.0,b'Law',...,0.14,3.0,2.0,4.0,7.0,6.0,0.0,b'1',b'0',b'0'
1,b'',female,21.0,22.0,b'Asian/Pacific Islander/Asian-American',b'European/Caucasian-American',b'0',2.0,4.0,b'Law',...,0.54,3.0,2.0,4.0,7.0,5.0,1.0,b'1',b'0',b'0'
2,b'',female,21.0,22.0,b'Asian/Pacific Islander/Asian-American',b'Asian/Pacific Islander/Asian-American',b'1',2.0,4.0,b'Law',...,0.16,3.0,2.0,4.0,7.0,NaN,1.0,b'1',b'1',b'1'
3,b'',female,21.0,23.0,b'Asian/Pacific Islander/Asian-American',b'European/Caucasian-American',b'0',2.0,4.0,b'Law',...,0.61,3.0,2.0,4.0,7.0,6.0,0.0,b'1',b'1',b'1'
4,b'',female,21.0,24.0,b'Asian/Pacific Islander/Asian-American',b'Latino/Hispanic American',b'0',2.0,4.0,b'Law',...,0.21,3.0,2.0,4.0,6.0,6.0,0.0,b'1',b'1',b'1'

In [31]:
for x in dirty_df.columns:
    dirty_df[x] = (
    dirty_df[x]
    .astype(str)
    .str.lstrip("b'")   # removes any leading b or '
    .str.rstrip("'")    # removes trailing '
)

In [32]:
dirty_df.head()

,has_null,gender,age,age_o,race,race_o,samerace,importance_same_race,importance_same_religion,field,...,interests_correlate,expected_happy_with_sd_people,expected_num_interested_in_me,expected_num_matches,like,guess_prob_liked,met,decision,decision_o,match
0,,female,21.0,27.0,Asian/Pacific Islander/Asian-American,European/Caucasian-American,0,2.0,4.0,Law,...,0.14,3.0,2.0,4.0,7.0,6.0,0.0,1,0,0
1,,female,21.0,22.0,Asian/Pacific Islander/Asian-American,European/Caucasian-American,0,2.0,4.0,Law,...,0.54,3.0,2.0,4.0,7.0,5.0,1.0,1,0,0
2,,female,21.0,22.0,Asian/Pacific Islander/Asian-American,Asian/Pacific Islander/Asian-American,1,2.0,4.0,Law,...,0.16,3.0,2.0,4.0,7.0,nan,1.0,1,1,1
3,,female,21.0,23.0,Asian/Pacific Islander/Asian-American,European/Caucasian-American,0,2.0,4.0,Law,...,0.61,3.0,2.0,4.0,7.0,6.0,0.0,1,1,1
4,,female,21.0,24.0,Asian/Pacific Islander/Asian-American,Latino/Hispanic American,0,2.0,4.0,Law,...,0.21,3.0,2.0,4.0,6.0,6.0,0.0,1,1,1

In [33]:
#lets find out how many values are missing
missing_pct = dirty_df.isna().mean() * 100
print(missing_pct.round(2))

has_null            0.0
gender              0.0
age                 0.0
age_o               0.0
race                0.0
                   ...
guess_prob_liked    0.0
met                 0.0
decision            0.0
decision_o          0.0
match               0.0
Length: 66, dtype: float64

In [34]:
# is nan
#lets find out how many values are missing
missing_pct = dirty_df.isnull().mean() * 100
print(missing_pct.round(2))

has_null            0.0
gender              0.0
age                 0.0
age_o               0.0
race                0.0
                   ...
guess_prob_liked    0.0
met                 0.0
decision            0.0
decision_o          0.0
match               0.0
Length: 66, dtype: float64

In [35]:
print(dirty_df.nunique())

has_null             1
gender               2
age                 25
age_o               25
race                 6
                    ..
guess_prob_liked    20
met                  8
decision             2
decision_o           2
match                2
Length: 66, dtype: int64

In [36]:
# i observed that their where 11 unique for some valuees even though their where only 10 options cz it was binary
dirty_df['shopping']

0       8.0
1       8.0
2       8.0
3       8.0
4       8.0
       ...
8373    7.0
8374    7.0
8375    7.0
8376    7.0
8377    7.0
Name: shopping, Length: 8378, dtype: object

In [37]:
dirty_df = dirty_df.replace('nan', np.nan)

In [38]:
#lets find out how many values are missing
missing_pct = dirty_df.isna().mean() * 100
print(missing_pct.round(2))

has_null            0.00
gender              0.00
age                 1.13
age_o               1.24
race                0.00
                    ...
guess_prob_liked    3.69
met                 4.48
decision            0.00
decision_o          0.00
match               0.00
Length: 66, dtype: float64

In [39]:
# option B: in-place
test = dirty_df.copy()          # if you donâ€™t want to mutate the original
test.dropna(inplace=True)
print(test.shape)

(1048, 66)

In [40]:
test.shape

(1048, 66)

In [41]:
dirty_df.shape

(8378, 66)

In [42]:
display(test)

,has_null,gender,age,age_o,race,race_o,samerace,importance_same_race,importance_same_religion,field,...,interests_correlate,expected_happy_with_sd_people,expected_num_interested_in_me,expected_num_matches,like,guess_prob_liked,met,decision,decision_o,match
0,,female,21.0,27.0,Asian/Pacific Islander/Asian-American,European/Caucasian-American,0,2.0,4.0,Law,...,0.14,3.0,2.0,4.0,7.0,6.0,0.0,1,0,0
1,,female,21.0,22.0,Asian/Pacific Islander/Asian-American,European/Caucasian-American,0,2.0,4.0,Law,...,0.54,3.0,2.0,4.0,7.0,5.0,1.0,1,0,0
3,,female,21.0,23.0,Asian/Pacific Islander/Asian-American,European/Caucasian-American,0,2.0,4.0,Law,...,0.61,3.0,2.0,4.0,7.0,6.0,0.0,1,1,1
4,,female,21.0,24.0,Asian/Pacific Islander/Asian-American,Latino/Hispanic American,0,2.0,4.0,Law,...,0.21,3.0,2.0,4.0,6.0,6.0,0.0,1,1,1
5,,female,21.0,25.0,Asian/Pacific Islander/Asian-American,European/Caucasian-American,0,2.0,4.0,Law,...,0.25,3.0,2.0,4.0,6.0,5.0,0.0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1836,,male,19.0,20.0,Asian/Pacific Islander/Asian-American,Other,0,4.0,1.0,Computer Science,...,0.35,5.0,0.0,0.0,5.0,1.0,0.0,0,0,0
1837,,male,19.0,21.0,Asian/Pacific Islander/Asian-American,European/Caucasian-American,0,4.0,1.0,Computer Science,...,0.45,5.0,0.0,0.0,5.0,1.0,0.0,0,0,0
1838,,male,19.0,20.0,Asian/Pacific Islander/Asian-American,Black/African American,0,4.0,1.0,Computer Science,...,0.13,5.0,0.0,0.0,5.0,1.0,0.0,0,0,0
1840,,male,19.0,21.0,Asian/Pacific Islander/Asian-American,European/Caucasian-American,0,4.0,1.0,Computer Science,...,0.54,5.0,0.0,0.0,5.0,1.0,0.0,0,0,0
1843,,male,19.0,20.0,Asian/Pacific Islander/Asian-American,Latino/Hispanic American,0,4.0,1.0,Computer Science,...,0.54,5.0,0.0,0.0,5.0,1.0,0.0,0,0,0

In [43]:
# 1. Examine % missing per column
miss_pct = dirty_df.isna().mean() * 100
print(miss_pct.sort_values(ascending=False))

# 2. Drop ultra-sparse columns (>50% missing)
cols_to_drop = miss_pct[miss_pct > 50].index
df2 = dirty_df.drop(columns=cols_to_drop)

# 3. Drop rows only if theyâ€™re still very sparse (>30% missing)
row_thresh = int(df2.shape[1] * 0.3)
df3 = df2.dropna(thresh=df2.shape[1] - row_thresh)

print("After cleanup:", df3.shape)

expected_num_interested_in_me    78.515159
expected_num_matches             14.000955
shared_interests_o               12.843161
shared_interests_partner         12.735736
ambitous_o                        8.617809
                                   ...
field                             0.000000
samerace                          0.000000
race_o                            0.000000
race                              0.000000
match                             0.000000
Length: 66, dtype: float64
After cleanup: (8293, 65)

In [44]:
df3

,has_null,gender,age,age_o,race,race_o,samerace,importance_same_race,importance_same_religion,field,...,yoga,interests_correlate,expected_happy_with_sd_people,expected_num_matches,like,guess_prob_liked,met,decision,decision_o,match
0,,female,21.0,27.0,Asian/Pacific Islander/Asian-American,European/Caucasian-American,0,2.0,4.0,Law,...,1.0,0.14,3.0,4.0,7.0,6.0,0.0,1,0,0
1,,female,21.0,22.0,Asian/Pacific Islander/Asian-American,European/Caucasian-American,0,2.0,4.0,Law,...,1.0,0.54,3.0,4.0,7.0,5.0,1.0,1,0,0
2,,female,21.0,22.0,Asian/Pacific Islander/Asian-American,Asian/Pacific Islander/Asian-American,1,2.0,4.0,Law,...,1.0,0.16,3.0,4.0,7.0,NaN,1.0,1,1,1
3,,female,21.0,23.0,Asian/Pacific Islander/Asian-American,European/Caucasian-American,0,2.0,4.0,Law,...,1.0,0.61,3.0,4.0,7.0,6.0,0.0,1,1,1
4,,female,21.0,24.0,Asian/Pacific Islander/Asian-American,Latino/Hispanic American,0,2.0,4.0,Law,...,1.0,0.21,3.0,4.0,6.0,6.0,0.0,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8373,,male,25.0,26.0,European/Caucasian-American,Latino/Hispanic American,0,1.0,1.0,Climate Dynamics,...,3.0,0.64,10.0,3.0,2.0,5.0,0.0,0,1,0
8374,,male,25.0,24.0,European/Caucasian-American,Other,0,1.0,1.0,Climate Dynamics,...,3.0,0.71,10.0,3.0,4.0,4.0,0.0,0,0,0
8375,,male,25.0,29.0,European/Caucasian-American,Latino/Hispanic American,0,1.0,1.0,Climate Dynamics,...,3.0,-0.46,10.0,3.0,6.0,5.0,0.0,0,0,0
8376,,male,25.0,22.0,European/Caucasian-American,Asian/Pacific Islander/Asian-American,0,1.0,1.0,Climate Dynamics,...,3.0,0.62,10.0,3.0,5.0,5.0,0.0,0,1,0
8377,,male,25.0,22.0,European/Caucasian-American,Asian/Pacific Islander/Asian-American,0,1.0,1.0,Climate Dynamics,...,3.0,0.01,10.0,3.0,4.0,5.0,0.0,0,1,0

In [45]:
df3.to_csv('cleaned_speeddating.csv', index=False)